name: Unittest & Quality

on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: requirements_test.txt
      - name: Tests
        run: pytest AliceCli/tests/ --cov=core/ --cov-report=xml
      - name: Fix paths
        run: sed -i 's/\/home\/runner\/work\/AliceCLI\/AliceCLI\//\/github\/workspace\//g' coverage.xml
      - name: Sonarcloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
